on:
  workflow_dispatch:
  push:

jobs:
  rebuild_droplet_job:
    runs-on: ubuntu-20.04
    name: Rebuild Digital Ocean Droplet
    steps:
    - name: Trigger droplet rebuild & wait for completion
      uses: chrisjsimpson/droplet-rebuild-action@v1
      timeout-minutes: 20
      with:
        digital-ocean-access-token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        droplet-id: ${{ secrets.DROPLET_ID }}
        image: ${{ secrets.IMAGE }}
